#!/usr/bin/env node
/**
 * Helper Script: Get Railway MySQL Connection Details
 * This helps you find your actual Railway MySQL credentials
 */

console.log(`
╔════════════════════════════════════════════════════════════════╗
║     How to Find Your Railway MySQL DATABASE_URL                ║
╚════════════════════════════════════════════════════════════════╝

STEP 1: Go to Railway Dashboard
   → Visit: https://railway.app
   → Login with your account

STEP 2: Open Your Project
   → Click on your project name
   → Go to the "Services" tab

STEP 3: Find MySQL Service
   → Look for the "MySQL" service in your project
   → Click on it to open the service details

STEP 4: Get Connection Variables
   → Click the "Variables" tab at the top
   → You should see these variables:
      • MYSQLHOST
      • MYSQLPORT
      • MYSQLUSER
      • MYSQLPASSWORD (or MYSQLSET_PASSWORD)
      • MYSQL_URL (or DATABASE_URL) - COPY THIS ONE!

STEP 5: Copy Your CONNECTION URL
   → The easiest way is to copy MYSQL_URL or look for DATABASE_URL
   → It should look like:
      mysql://root:actualPassword123@metro.proxy.rlwy.net:25385/railway

STEP 6: Use It in Terminal
   → Open PowerShell and run:
   
   $env:DATABASE_URL="mysql://root:YOUR_PASSWORD_HERE@metro.proxy.rlwy.net:25385/railway"
   node fix_subject_teachers_columns.cjs

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚠️  IMPORTANT NOTES:
   • The password is NOT "PASSWORD" - it's a real password generated by Railway
   • Copy it EXACTLY as shown (special characters and all)
   • If your password has special chars like @ or :
     You may need to URL-encode them:
     @ = %40
     : = %3A
     # = %23

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EXAMPLE (if password is ABC@123#XYZ):
   
   $env:DATABASE_URL="mysql://root:ABC%40123%23XYZ@metro.proxy.rlwy.net:25385/railway"
   node fix_subject_teachers_columns.cjs

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💡 TIP: If you see "MYSQL_URL" in Railway variables, it's usually already
   formatted correctly with the password. Just copy it directly!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`);
