[phases.setup]
nixPkgs = ["nodejs_23"]

[phases.install]
cmds = ["rm -f package-lock.json", "npm install --include=dev", "cd server && npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node server/server.js"
